export const CREATE_ITEM = 'CREATE_ITEM'
export const UPDATE_ITEM = 'UPDATE_ITEM'
export const DELETE_ITEM = 'DELETE_ITEM'
export const STOCK_PLUS_ITEM = 'STOCK_PLUS_ITEM'
export const STOCK_MINUS_ITEM = 'STOCK_MINUS_ITEM'
export const SORT_ITEMS_WITH_LABEL = 'SORT_ITEMS_WITH_LABEL'
export const SORT_ITEMS_WITH_ITEM_NAME = 'SORT_ITEMS_WITH_ITEM_NAME'
export const SORT_ITEMS_WITH_STOCK_FEW = 'SORT_ITEMS_WITH_STOCK_FEW'
export const SORT_ITEMS_WITH_STOCK_MANY = 'SORT_ITEMS_WITH_STOCK_MANY'
export const SORT_ITEMS_WITH_DEADLINE_SHORT = 'SORT_ITEMS_WITH_DEADLINE_SHORT'
export const SORT_ITEMS_WITH_DEADLINE_LONG = 'SORT_ITEMS_WITH_DEADLINE_LONG'
export const DELETE_ALL_ITEMS = 'DELETE_ALL_ITEMS'

export const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES'
export const DELETE_ALL_CATEGORIES = 'DELETE_ALL_CATEGORIES'

export const UPDATE_MAIL_ADDRESS = 'UPDATE_MAIL_ADDRESS'
// export const AUTO_MAIL = 'AUTO_MAIL' // 未実装(自動メール設定機能)
export const DELETE_MAIL_ADDRESS = 'DELETE_MAIL_ADDRESS'

